In [105]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [106]:
# Leitura do arquivo xlsx

df_analise = pd.read_excel("analise_funcionarios.xlsx")
display(df_analise)

,Nome,Idade,Departamento,Salario,Satisfacao,Desempenho,Motivo_Desligamento
0,Tatiane Junqueira,48.0,VENDAS,5365.24,Média,3.9,NaN
1,Danilo Martins,31.0,Financeiro,6458.34,Baixa,8.7,NaN
2,Viviane Xavier,27.0,RH,3301.39,Média,6.7,NaN
3,Leandro Henriques,52.0,Financeiro,8844.01,Média,7.5,NaN
4,Rafael Martins,33.0,RH,5482.92,Média,4.9,NaN
...,...,...,...,...,...,...,...
178,Fábio Barros,48.0,RH,6504.81,Alta,NaN,Desempenho
179,Isabela Vieira,43.0,Operações,3425.28,Média,8.4,NaN
180,Henrique Queiroz,55.0,RH,8462.49,Média,6.7,NaN
181,Yasmin Xavier,37.0,Operações,2650.06,Média,7.9,NaN
182,Fábio Xavier,25.0,Vendas,4797.96,Alta,6.5,NaN

In [107]:
# Desmembrar a tabela

display(df_analise.shape)
display(df_analise.info())
display (df_analise.columns)
display(df_analise.describe())

(183, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nome                 183 non-null    object
 1   Idade                181 non-null    float64
 2   Departamento         183 non-null    object
 3   Salario              183 non-null    float64
 4   Satisfacao           180 non-null    object
 5   Desempenho           178 non-null    float64
 6   Motivo_Desligamento  37 non-null     object
dtypes: float64(3), object(4)
memory usage: 10.1+ KB

None

Index(['Nome', 'Idade', 'Departamento', 'Salario', 'Satisfacao', 'Desempenho',
       'Motivo_Desligamento'],
      dtype='object')

            Idade       Salario  Desempenho
count  181.000000    183.000000  178.000000
mean    41.596685   5928.445082    6.464607
std     14.388181   2033.368816    1.908066
min     20.000000   2419.640000    3.000000
25%     31.000000   4327.970000    4.925000
50%     42.000000   5602.540000    6.600000
75%     50.000000   7311.535000    8.100000
max    150.000000  12018.650000    9.900000

In [108]:
# Padronização

df_analise["Nome"] = df_analise["Nome"].str.title().str.strip()

df_analise["Departamento"] = df_analise["Departamento"].str.title().str.strip()

padronizar_departamentos = {
    "T.I": "TI",
    "T.i": "TI",
    "T.i.": "TI",
    "T.I.": "TI",
    "Ti": "TI",
    "Tecnologia da Informação": "TI",
    "Tecnologia Da Informação": "TI",
    "Rh": "RH",
    "Recursos Humanos": "RH"
}

df_analise["Departamento"] = df_analise["Departamento"].replace(padronizar_departamentos)

display(df_analise)

,Nome,Idade,Departamento,Salario,Satisfacao,Desempenho,Motivo_Desligamento
0,Tatiane Junqueira,48.0,Vendas,5365.24,Média,3.9,NaN
1,Danilo Martins,31.0,Financeiro,6458.34,Baixa,8.7,NaN
2,Viviane Xavier,27.0,RH,3301.39,Média,6.7,NaN
3,Leandro Henriques,52.0,Financeiro,8844.01,Média,7.5,NaN
4,Rafael Martins,33.0,RH,5482.92,Média,4.9,NaN
...,...,...,...,...,...,...,...
178,Fábio Barros,48.0,RH,6504.81,Alta,NaN,Desempenho
179,Isabela Vieira,43.0,Operações,3425.28,Média,8.4,NaN
180,Henrique Queiroz,55.0,RH,8462.49,Média,6.7,NaN
181,Yasmin Xavier,37.0,Operações,2650.06,Média,7.9,NaN
182,Fábio Xavier,25.0,Vendas,4797.96,Alta,6.5,NaN

In [109]:
# Tratamento de dados duplicados ou erros

duplicadas = df_analise.duplicated()
display(duplicadas)

total_duplicadas = df_analise.duplicated().sum()
display(total_duplicadas)

linhas_repetidas = df_analise[df_analise.duplicated()]
display(linhas_repetidas)

df_analise = df_analise.drop(df_analise[df_analise["Nome"] == "Xênia Henriques"].index)

df_analise = df_analise.drop_duplicates(subset=["Nome","Idade","Salario"])
display(df_analise)

0      False
1      False
2      False
3      False
4      False
       ...
178    False
179    False
180    False
181    False
182    False
Length: 183, dtype: bool

np.int64(3)

,Nome,Idade,Departamento,Salario,Satisfacao,Desempenho,Motivo_Desligamento
16,Natália Duarte,56.0,Vendas,6173.23,Média,4.5,Reestruturação
61,Leandro Vieira,29.0,Operações,4092.90,Média,8.6,Fim de contrato
111,Gustavo Xavier,28.0,RH,4613.18,Baixa,3.5,NaN

,Nome,Idade,Departamento,Salario,Satisfacao,Desempenho,Motivo_Desligamento
0,Tatiane Junqueira,48.0,Vendas,5365.24,Média,3.9,NaN
1,Danilo Martins,31.0,Financeiro,6458.34,Baixa,8.7,NaN
2,Viviane Xavier,27.0,RH,3301.39,Média,6.7,NaN
3,Leandro Henriques,52.0,Financeiro,8844.01,Média,7.5,NaN
4,Rafael Martins,33.0,RH,5482.92,Média,4.9,NaN
...,...,...,...,...,...,...,...
178,Fábio Barros,48.0,RH,6504.81,Alta,NaN,Desempenho
179,Isabela Vieira,43.0,Operações,3425.28,Média,8.4,NaN
180,Henrique Queiroz,55.0,RH,8462.49,Média,6.7,NaN
181,Yasmin Xavier,37.0,Operações,2650.06,Média,7.9,NaN
182,Fábio Xavier,25.0,Vendas,4797.96,Alta,6.5,NaN

In [110]:
# Tratamento de linhas vazias em colunas string 

df_analise = df_analise.copy()

df_analise["Satisfacao"] = df_analise["Satisfacao"].fillna("Não informado")

df_analise["Motivo_Desligamento"] = df_analise["Motivo_Desligamento"].fillna("Funcionário Ativo")

display(df_analise)

,Nome,Idade,Departamento,Salario,Satisfacao,Desempenho,Motivo_Desligamento
0,Tatiane Junqueira,48.0,Vendas,5365.24,Média,3.9,Funcionário Ativo
1,Danilo Martins,31.0,Financeiro,6458.34,Baixa,8.7,Funcionário Ativo
2,Viviane Xavier,27.0,RH,3301.39,Média,6.7,Funcionário Ativo
3,Leandro Henriques,52.0,Financeiro,8844.01,Média,7.5,Funcionário Ativo
4,Rafael Martins,33.0,RH,5482.92,Média,4.9,Funcionário Ativo
...,...,...,...,...,...,...,...
178,Fábio Barros,48.0,RH,6504.81,Alta,NaN,Desempenho
179,Isabela Vieira,43.0,Operações,3425.28,Média,8.4,Funcionário Ativo
180,Henrique Queiroz,55.0,RH,8462.49,Média,6.7,Funcionário Ativo
181,Yasmin Xavier,37.0,Operações,2650.06,Média,7.9,Funcionário Ativo
182,Fábio Xavier,25.0,Vendas,4797.96,Alta,6.5,Funcionário Ativo

In [111]:
# Criação de novas colunas e posicionamento das colunas

def avaliar_desempenho(Desempenho):
    if pd.isna(Desempenho):
        return "Indisponível"

    elif Desempenho >= 9.0:
        return "Excelente Desempenho"
    
    elif Desempenho >= 7.0:
        return "Bom Desempenho"
    
    else:
        return "Desempenho Insatisfatório"


df_analise["Avaliação"] = df_analise["Desempenho"].apply(avaliar_desempenho)

def avaliar_salario(Salario):
    if Salario >= 10000.00:
        return "Salário Muito Alto"

    elif Salario >= 6000.00:
        return "Salário Alto"

    else:
        return "Salário Padrão"


df_analise["Faixa Salarial"] = df_analise ["Salario"].apply(avaliar_salario)

ordem_colunas = [
     "Nome", "Idade", "Departamento", "Salario", "Faixa Salarial", 
    "Desempenho", "Avaliação", "Satisfacao", "Motivo_Desligamento"
]

df_analise = df_analise [ordem_colunas]

display(df_analise)

,Nome,Idade,Departamento,Salario,Faixa Salarial,Desempenho,Avaliação,Satisfacao,Motivo_Desligamento
0,Tatiane Junqueira,48.0,Vendas,5365.24,Salário Padrão,3.9,Desempenho Insatisfatório,Média,Funcionário Ativo
1,Danilo Martins,31.0,Financeiro,6458.34,Salário Alto,8.7,Bom Desempenho,Baixa,Funcionário Ativo
2,Viviane Xavier,27.0,RH,3301.39,Salário Padrão,6.7,Desempenho Insatisfatório,Média,Funcionário Ativo
3,Leandro Henriques,52.0,Financeiro,8844.01,Salário Alto,7.5,Bom Desempenho,Média,Funcionário Ativo
4,Rafael Martins,33.0,RH,5482.92,Salário Padrão,4.9,Desempenho Insatisfatório,Média,Funcionário Ativo
...,...,...,...,...,...,...,...,...,...
178,Fábio Barros,48.0,RH,6504.81,Salário Alto,NaN,Indisponível,Alta,Desempenho
179,Isabela Vieira,43.0,Operações,3425.28,Salário Padrão,8.4,Bom Desempenho,Média,Funcionário Ativo
180,Henrique Queiroz,55.0,RH,8462.49,Salário Alto,6.7,Desempenho Insatisfatório,Média,Funcionário Ativo
181,Yasmin Xavier,37.0,Operações,2650.06,Salário Padrão,7.9,Bom Desempenho,Média,Funcionário Ativo
182,Fábio Xavier,25.0,Vendas,4797.96,Salário Padrão,6.5,Desempenho Insatisfatório,Alta,Funcionário Ativo

In [112]:
# Métricas

# .1 - MÉTRICAS SALÁRIO

# .1.1 - Salário Total

salario_total = df_analise["Salario"].sum()

# .1.2 - Salário Médio

salario_medio = df_analise["Salario"].mean() 

# .1.3 - Maior Salário

idx_maior_salario = df_analise["Salario"].idxmax()

nome_maior_salario = df_analise.loc[idx_maior_salario, "Nome"]

valor_maior_salario = df_analise.loc[idx_maior_salario, "Salario"]

# .1.4 - Menor Salário

idx_menor_salario = df_analise["Salario"].idxmin()

nome_menor_salario = df_analise.loc[idx_menor_salario, "Nome"]

valor_menor_salario = df_analise.loc[idx_menor_salario, "Salario"]
# ----------------------------------------------------------------------------------------------

# .2 - MÉTRICAS DESEMPENHO

# .2.1 - Desempenho Médio

media_desempenho = df_analise["Desempenho"].mean() 

# .2.2 - Maior Desempenho

idx_maior_desempenho = df_analise["Desempenho"].idxmax()

pessoa_maior_desempenho = df_analise.loc[idx_maior_desempenho, "Nome"]

nota_maior_desempenho = df_analise.loc[idx_maior_desempenho, "Desempenho"]

# .2.3 - Menor Desempenho

idx_menor_desempenho = df_analise["Desempenho"].idxmin()

pessoa_menor_desempenho = df_analise.loc[idx_menor_desempenho, "Nome"]

nota_menor_desempenho = df_analise.loc[idx_menor_desempenho, "Desempenho"]
# ----------------------------------------------------------------------------------------------

# .3 - MÉTRICAS IDADE

# .3.1 - Média de Idade

média_idade = df_analise["Idade"].mean()

# .3.2 - Maior Idade

idx_maior_idade = df_analise["Idade"].idxmax()

nome_maior_idade = df_analise.loc[idx_maior_idade, "Nome"]

numero_maior_idade = df_analise.loc[idx_maior_idade, "Idade"]

# .3.3 - Menor Idade

idx_menor_idade = df_analise["Idade"].idxmin()

nome_menor_idade = df_analise.loc[idx_menor_idade, "Nome"]

numero_menor_idade = df_analise.loc[idx_menor_idade, "Idade"]
# ----------------------------------------------------------------------------------------------

# .4 - MÉTRICAS DEPARTAMENTO

# .4.1 - Maior Departamento

contagem_departamento = df_analise["Departamento"].value_counts()

nome_maior_departamento = contagem_departamento.idxmax()

qtd_maior_departamento = contagem_departamento.max()

# .4.2 - Menor Departamento

contagem_departamento = df_analise["Departamento"].value_counts()

nome_menor_departamento = contagem_departamento.idxmin()

qtd_menor_departamento = contagem_departamento.min()
# ----------------------------------------------------------------------------------------------

# Resumo

df_resumo_geral = pd.DataFrame({
    "Indicador": [
        "Salário Total", 
        "Salário Médio",
        "Maior Salário",
        "Menor Salário",
        "Desempenho Médio", 
        "Maior Desempenho", 
        "Menor Desempenho", 
        "Média de Idade", 
        "Pessoa Mais Velha", 
        "Pessoa Mais Nova",
        "Maior Departamento",
        "Menor Departamento"
    ],
    "Resultado": [
        f"R$ {salario_total:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."),
        f"R$ {salario_medio:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."),
        f"R$ {valor_maior_salario:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."),
        f"R$ {valor_menor_salario:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."),
        f"{media_desempenho:.2f}".replace(".", ","),
        f"{pessoa_maior_desempenho} ({f'{nota_maior_desempenho:.2f}'.replace('.', ',')})",
        f"{pessoa_menor_desempenho} ({f'{nota_menor_desempenho:.2f}'.replace('.', ',')})",
        f"{média_idade:.1f} anos".replace(".", ","),
        f"{nome_maior_idade} ({int(numero_maior_idade)} anos)",
        f"{nome_menor_idade} ({int(numero_menor_idade)} anos)",
        f"{nome_maior_departamento} ({int(qtd_maior_departamento)} funcionários)",
        f"{nome_menor_departamento} ({int(qtd_menor_departamento)} funcionários)"
    ]
})
display(df_resumo_geral)

             Indicador                    Resultado
0        Salário Total              R$ 1.064.506,73
1        Salário Médio                  R$ 5.946,96
2        Maior Salário                 R$ 12.018,65
3        Menor Salário                  R$ 2.419,64
4     Desempenho Médio                         6,47
5     Maior Desempenho          Wagner Souza (9,90)
6     Menor Desempenho       Diego Henriques (3,00)
7       Média de Idade                    41,1 anos
8    Pessoa Mais Velha     Rafael Cardoso (60 anos)
9     Pessoa Mais Nova   Leandro Teixeira (20 anos)
10  Maior Departamento         RH (37 funcionários)
11  Menor Departamento  Marketing (27 funcionários)

In [113]:
# Planilha Final

display(
    df_analise.style.format(
        {
        "Desempenho": "{:.1f}",
        "Idade": "{:.0f}",
        "Salario": lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".") if pd.notna(x) else "Não informado"
        },  
    )
)

display(df_resumo_geral.style)

In [117]:
# Exportação pro Excel

df_analise_estilizado = df_analise.style.format(
    {
        "Desempenho": "{:.1f}",
        "Idade": "{:.0f}",
        "Salario": lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".") if pd.notna(x) else x
    }
)


nome_arquivo = "Analise_Final_Tratada.xlsx"

with pd.ExcelWriter(nome_arquivo) as writer:
    df_analise_estilizado.to_excel(writer, sheet_name="Dados Tratados", index=False, na_rep="Não Informado")
    df_resumo_geral.to_excel(writer, sheet_name="Resumo Indicadores", index=False)

print(f"\n Sucesso! O arquivo '{nome_arquivo}' foi gerado e as células vazias agora dizem 'Não Informado' no Excel.")

 Sucesso! O arquivo 'Analise_Final_Tratada.xlsx' foi gerado e as células vazias agora dizem 'Não Informado' no Excel.